Separate local from global bin installs
Also, have shellfuncs only display an error if something
went wrong with the install. This is because I found it annoying
to see the shellfuncs success message and the dotfiles
success message.

Have each init script output some success message. This is so
I am reminded of what else is going on when dotfiles are installed.

diff --git a/init/install-shellfuncs b/init/install-shellfuncs
--- a/init/install-shellfuncs
+++ b/init/install-shellfuncs
@@ -18,7 +18,12 @@ fi
 if [ -z "$SHELLFUNCS_REPO_PATH" ]; then
     curl --output "$SHELLFUNCS_INSTALL_PROGRAM_NAME" --silent "$SHELLFUNCS_INSTALL_PROGRAM_URL"
     chmod 755 "$SHELLFUNCS_INSTALL_PROGRAM_NAME"
-    ./"${SHELLFUNCS_INSTALL_PROGRAM_NAME}"
+    if ! ./"${SHELLFUNCS_INSTALL_PROGRAM_NAME}" > /dev/null 2>&1; then
+        echo "$ERROR something went wrong with the shellfuncs install!"
+        exit 1
+    fi
 fi
+
+echo -e "$SUCCESS 'shellfuncs' was installed"
 
 exit 0
